name: jank_scout
description: A performance-optimized, zero-dependency frame drop (jank) interception package for local Flutter development.
version: 0.0.2
repository: https://github.com/umarKhan1/jank_scout
issue_tracker: https://github.com/umarKhan1/jank_scout/issues
topics:
  - performance
  - profiling
  - jank
  - monitoring
  - devtools

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
